# Generated by Django 2.0.7 on 2019-06-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20190604_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='seats',
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_id',
            field=models.IntegerField(default=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='parking_name',
            field=models.CharField(default='NDK', max_length=256),
        ),
        migrations.AddField(
            model_name='bike',
            name='reservator',
            field=models.CharField(default='None', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='current_owner',
            field=models.CharField(default='None', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
    ]
