# Generated by Django 2.0.7 on 2019-06-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20190604_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='parking_name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='reservator',
        ),
        migrations.AddField(
            model_name='bike',
            name='seats',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='current_owner',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='reserved',
            field=models.IntegerField(),
        ),
    ]
